[BankList]
BankList=Synth, Vocal, Plucked, Wind, String, Key

[Banks]
Key=Bass-Clave, Bright_Bass-Clave, Marimba-MusicBox, Club_Piano, Mellow_Club_Piano, BellRhodeX, PerOrgan, DetunedOrgan, Organillo
Plucked=Sitar, CedroGuitar, OldGuitar, ToyGuitar, Harp
String=Orchestra_Ensamble, Medieval_Strings
Synth=InsideTank, PLuckVoco, Taflu, BassWa, Rhythmic_Attack
Vocal=AnaVoice, Antique_Voices
Wind=80SlowWinds, Trumpet, Saxo, Oriental_Wood_Winds

[PresetList]
PresetList=@Invalid()

[Presets]
80SlowWinds=80SlowWinds.samplv1
AnaVoice=AnaVoice.samplv1
Antique_Voices=Antique_Voices.samplv1
Bass-Clave=Bass-Clave.samplv1
BassWa=BassWa.samplv1
BellRhodeX=BellRhodeX.samplv1
Bright_Bass-Clave=Bright_Bass-Clave.samplv1
CedroGuitar=CedroGuitar.samplv1
Club_Piano=Club_Piano.samplv1
DetunedOrgan=DetunedOrgan.samplv1
Harp=Harp.samplv1
InsideTank=InsideTank.samplv1
Marimba-MusicBox=Marimba-MusicBox.samplv1
Medieval_Strings=Medieval_Strings.samplv1
Mellow_Club_Piano=Mellow_Club_Piano.samplv1
OldGuitar=OldGuitar.samplv1
Orchestra_Ensamble=Orchestra_Ensamble.samplv1
Organillo=Organillo.samplv1
Oriental_Wood_Winds=Oriental_Wood_Winds.samplv1
PLuckVoco=PLuckVoco.samplv1
PerOrgan=PerOrgan.samplv1
Rhythmic_Attack=Rhythmic_Attack.samplv1
Saxo=Saxo.samplv1
Sitar=Sitar.samplv1
Taflu=Taflu.samplv1
ToyGuitar=ToyGuitar.samplv1
Trumpet=Trumpet.samplv1
